#!/bin/sh
cd /boot/home/projects/FuzzyTime/PackagingFolder
package create -b fuzzytime_0.1.1-5_gcc2.hpkg
sleep 0.5
package add fuzzytime_0.1.1-5_gcc2.hpkg data apps bin documentation
sleep 0.5
addattr BeShare:Info "Desktop applet to display the date and time in 'fuzzy' format" fuzzytime_0.1.1-5_gcc2.hpkg
becopy fuzzytime_0.1.1-5_gcc2.hpkg "/Storage/Haiku/My ports"
mv fuzzytime_0.1.1-5_gcc2.hpkg /boot/home/projects/repo
